data_paths:
  source_folder: "/path/to/source/folder"
  cropped_folder: "/path/to/cropped/folder"
  color_amp_folder: "/path/to/color/amplified/folder"
  motion_amp_folder: "/path/to/motion/amplified/folder"
  generated_data_folder: "/path/to/generated/data/folder"
  trajectories_path: "/path/to/trajectories"
  video_directory: "/path/to/video/directory"
  gt_folder: "/path/to/ground_truth/folder"
  vid_folder: "/path/to/video/folder"
  model_data: "/path/to/model/data"
  target_csv: "/path/to/target.csv"
  model_save_path: "/path/to/save/model"
  results_folder: "/path/to/results"

video_processing:
  pyramid_levels: 5
  final_video_length: 10
  lowcut: 0.5
  highcut: 5.0
  order: 5
  pixel_width: 3
  fps: 30
  plot: false

training:
  seed: 12345
  batch_size: 3
  epochs: 2
  optimizer: "adam"
  learning_rate: 0.001
  test_split: 0.2
  lopo: "subject_id" # Replace with actual subject ID

model:
  type: "CnnRegressor"
  input_channels: 3
  output_units: 1

experiment:
  type: "LOPO"  # Options: "LOPO", "LOPO_with_Samples", "Same_Person"

cropping:
  min_height: 10000
  min_width: 10000
  cascade_path: "/path/to/haarcascade_frontalface_alt.xml"

classification:
  solver: "sgd"
  hidden_layers: [200, 200, 200, 200, 200, 200]
  momentum: 0.9

output:
  results_csv_path: "/path/to/save/results.csv"